### ISSUE TITLE
explain criteria for the chosen 100 papers

### ISSUE THREAD

**Issue by awakenting** [OpenKnowledgeMaps/project-website#13]
Hey,
it would be nice if you would explain based on which criteria the 100 papers are chosen. Is it text matches with the search term only or also number of citations or some mixture ? I guess this is still work in progress but I think it makes sense to make this transparent :) (Maybe it's possible to extract the core parts of the algorithm automatically ?)

**Comment by pkraker** [comment]
Good suggestion. At the moment, we are using the relevance ranking provided by - depending on your cboice - either the DOAJ API or the PubMed API. Both of them mainly use text similarity. PubMed has a [detailed description of their relevance ranking](https://www.ncbi.nlm.nih.gov/books/NBK3827/#pubmedhelp.Computation_of_Weighted_Relev). DOAJ uses ElasticSearch, which describe their ranking as well [on this page](https://www.elastic.co/guide/en/elasticsearch/guide/current/relevance-intro.html). We'll add an explanation to the site.

**Comment by awakenting** [comment]
Ah I see. Thanks for the references.

**Comment by pkraker** [comment]
The explanation has been added to the website's new FAQ section: https://openknowledgemaps.org/faqs.php
