### ISSUE TITLE
Tracking blockers break functionality of the site

### ISSUE THREAD

**Issue by pkraker** [OpenKnowledgeMaps/project-website#20]
Tracking blockers, including the [EFF Privacy Badger](https://www.eff.org/privacybadger) and ublock with certain lists enabled, prevent users from searching on the site. After clicking on the search button, they get redirected back to the index page.

**Comment by BitKnitting** [comment]
I use and support EFF privacy badger.  I hope to be able to use OpenKnowledgeMaps once this issue is resolved.  Peter - thank you for opening this issue.

**Comment by rvidal** [comment]
Along with the help of @gorhill, it seems like it's a custom list that is causing this issue. More specifically, it is the Fanboy's Annoyance List from EasyList.to
By removing the list from uBlock Origin, the issue no longer persists.
