### ISSUE TITLE
Privacy Badger - 2016.12.7.2

### ISSUE THREAD

**Issue by Martin818** [OpenKnowledgeMaps/project-website#21]
Privacy Badger just broke in my Chrome Browser. (Browser is up-to-date version.) This morning got a flag that a new version of Badger was installed, it didn't work. (Badger version 2016.12.7.2)

When I go to Chrome extension, repair is in red. I click "repair" and it is never fixed. I uninstalled and reinstalled...same problem. 

How to I get it repaired and working again?

**Comment by pkraker** [comment]
Sorry, but you've got the wrong Github repository. You probably want go here: https://github.com/EFForg/privacybadger
