### ISSUE TITLE
Font salad in visualization

### ISSUE THREAD

**Issue by Daniel-Mietchen** [OpenKnowledgeMaps/project-website#25]
In https://openknowledgemaps.org/map/03c06165413c395e8c56206396bb7b13 ,
some bubbles don't display fonts properly.

Some others display fine but in various languages I did not search for. This is actually a nice feature but it would be good to have that as an option rather than by default.

**Comment by pkraker** [comment]
Thanks. These issues are discussed in more detail in OpenKnowledgeMaps/Headstart#156 and OpenKnowledgeMaps/Headstart#159.

**Comment by tanteuschi** [comment]
We will keep track of this in Headstart.
