### ISSUE TITLE
Make backlinks to BASE functional

### ISSUE THREAD

**Issue by Daniel-Mietchen** [OpenKnowledgeMaps/project-website#26]
as per https://github.com/Daniel-Mietchen/events/commit/de92ca6ef10f60ce3c2ddd7502f2e7addf23e804

**Comment by pkraker** [comment]
Thanks for this. Backlinks to BASE are, however, indeed functional. For your search term, no results are found with the OKMaps default options for BASE (document types: journal articles only, verbatim search). If you set the options to all document types and additional word forms (which you essentially did when trimming the URL parameters), you get results, but still not enough to create a map (they are mostly duplicates from the same paper, which we deduplicate as part of the process).

Currently, OKMaps is simply not set up for longer queries. But regarding the help screen, we should definitely include a note that makes users aware of this along with the suggestion to broaden the document types. Would this have helped your search?

**Comment by tanteuschi** [comment]
This is now fixed. Better error messages have been moved to a separate issue.
