### ISSUE TITLE
Allow more complex search strings

### ISSUE THREAD

**Issue by Daniel-Mietchen** [OpenKnowledgeMaps/project-website#27]
Right now, the search seems to break for queries like
> A Pattern-Based Method for Identifying and Analyzing Laws

(cf. https://github.com/Daniel-Mietchen/events/commit/de92ca6ef10f60ce3c2ddd7502f2e7addf23e804 )
but in principle, it should be possible to generate more specific Open Knowledge Maps by starting from a sample text describing the search topic rather than just simple search terms.

And if the search term is the title of a paper (as in the example above), I would expect that paper to show up in the results, along with related ones.

**Comment by tanteuschi** [comment]
The search query "A Pattern-Based Method for Identifying and Analyzing Laws" works now (you need to set filter to all doc types): https://openknowledgemaps.org/map/59199da8a906df635f39cd5e6044ea34

The "related documents" feature is a separate use case. I will open a new issue for this one in https://github.com/OpenKnowledgeMaps/Headstart.
