### ISSUE TITLE
Closing the beta notification while the map hasn't fully loaded causes redirect to search page

### ISSUE THREAD

**Issue by Bubblbu** [OpenKnowledgeMaps/project-website#33]
![peek 2018-07-02 17-20](https://user-images.githubusercontent.com/6946077/42192255-8af10446-7e1c-11e8-87a9-bbc3c2add974.gif)

**Comment by pkraker** [comment]
I couldn't reproduce this issue any more. @Bubblbu can you please check if it is resolved for you as well?

**Comment by Bubblbu** [comment]
Still happening for me. Tested with Firefox and Chrome.

The issue is that the [x] is linking to "https://openknowledgemaps.org/#" and replaced with a link to, e.g., "https://openknowledgemaps.org/map/f639da2db1e03a664b3d8592fa255275" at a later point

Wondering if that element needs href at all?
