### ISSUE TITLE
it would be nice to have a more detailed "How it works section"

### ISSUE THREAD

**Issue by underthecurve** [OpenKnowledgeMaps/project-website#8]
For example, it is not clear at first that you are pulling in only the top 100 results. Also that you define "top 100" as the 100 most relevant results according to the search engines themselves.

**Comment by underthecurve** [comment]
Also, maybe have a toggle option between "top 100" vs "top 50", for instance

**Comment by pkraker** [comment]
Thanks, we'll look into clarifying this section.

**Comment by pkraker** [comment]
We've added much more information to the website now, including links to papers and repositiories with further insights. Check out: https://openknowledgemaps.org/about.php
